spring.application.name=ASpringSecurityDemo



spring.security.oauth2.client.registration.google.client-id=759063810367-4rcjoj5s9ss0rvscerhbj56e0kvm8715.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

## gitHub
#spring.security.oauth2.client.registration.github.client-id=Ov23liy2ozbNbgrF6tIp
#spring.security.oauth2.client.registration.github.client-secret=b7e39cfe454866b9f92398cc0627a748eb18a91

